basePath: /
definitions:
  handlers.FizzBuzzOutput:
    properties:
      result:
        items:
          type: string
        type: array
    type: object
  handlers.PingOutput:
    properties:
      git_hash:
        type: string
      message:
        type: string
    type: object
  stats.Count:
    properties:
      hit:
        type: integer
      key:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a custom FizzBuzz HTTP server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FizzBuzz API
  version: "1.0"
paths:
  /fizzbuzz:
    get:
      consumes:
      - '*/*'
      description: Get your own version of the fizzbuzz algortihm.
      parameters:
      - default: 3
        description: fizzbuzz's first multiple
        in: query
        minimum: 1
        name: int1
        type: integer
      - default: 5
        description: fizzbuzz's second multiple
        in: query
        minimum: 1
        name: int2
        type: integer
      - default: fizz
        description: fizzbuzz's first replacement
        in: query
        name: str1
        type: string
      - default: buzz
        description: fizzbuzz's second replacement
        in: query
        name: str2
        type: string
      - default: 100
        description: fizzbuzz's up-to value
        in: query
        minimum: 0
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.FizzBuzzOutput'
      summary: Customizable fizzbuzz algorithm.
      tags:
      - fizzbuzz
  /fizzbuzz/stats:
    get:
      consumes:
      - '*/*'
      description: Get the 100 most used parameters on GET /fizbuzz route.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/stats.Count'
            type: array
      summary: Top 100 /fizzbuzz parameters.
      tags:
      - fizzbuzz
  /mon/ping:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingOutput'
      summary: Show the status of server.
      tags:
      - monitoring
schemes:
- http
swagger: "2.0"
