name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Lint - govet
      run: go vet ./...

    - name: Lint - gofmt
      run: gofmt -s -l . || (echo "files should comply with gofmt -s" && exit 1)

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
